trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  PHP_VERSION: 7.4

services:
  mysql:
    image: mysql:5.7
    env:
      MYSQL_ROOT_PASSWORD: DistroCode@231
      MYSQL_DATABASE: u919981075_pcparts_db
    ports:
      - 3306:3306
    options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

steps:
 
 

  - script: |
     
  - script: |
      php artisan test
    displayName: 'Run tests'
